### ISSUE TITLE
Error in server console

### ISSUE THREAD

**Issue by MickaNoob** [phara1/advanced-ff-cs2#2]
Hi, just for you an error in my console.
```

16:07:37 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AdvancedFriendlyFire.AdvancedFriendlyFire.OnPlayerHurt(EventPlayerHurt eventInfo, GameEventInfo info) in S:\ROGLX NETWORK\server\scripts_tomade\Advanced Friendly Fire\advanced_friendlyfire.cs:line 97
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by phara1** [comment]
I’ll be checking as soon as I get home from work. Besides that, have you faced any other issues besides this?

**Comment by phara1** [comment]
Pushed an update to fix this error. Let me know if you encounter the same issue.

**Comment by crashzk** [comment]
@phara1 I sent the latest version, but the plugin doesn't start. No error logs or anything, the plugin just doesn't start.

I've already restarted the server and still nothing.
