### ISSUE TITLE
Error in console 2 (Bomb issue I think)

### ISSUE THREAD

**Issue by MickaNoob** [phara1/advanced-ff-cs2#3]
`23:13:29 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AdvancedFriendlyFire.AdvancedFriendlyFire.OnPlayerHurt(EventPlayerHurt eventInfo, GameEventInfo info) in S:\ROGLX NETWORK\server\scripts_tomade\Advanced Friendly Fire\advanced_friendlyfire.cs:line 101
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
`

Hello, this error is not fixed, 
I've noticed it's present when a player dies from the bomb. If it helps you

Have a nice day !

**Comment by phara1** [comment]
https://github.com/phara1/advanced-ff-cs2/releases/tag/v1.1.2
This should fix it, let me know if you encounter any issues

**Comment by MickaNoob** [comment]
I will try it 

Thanks

**Comment by crashzk** [comment]
Fix

**Comment by phara1** [comment]
> Fix

Closed as issue is now fixed
