### ISSUE TITLE
[EROR] (cssharp:Core) Error invoking callback System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by crashzk** [phara1/advanced-ff-cs2#4]
```
2024-10-06 12:31:10.818 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AdvancedFriendlyFire.AdvancedFriendlyFire.OnPlayerHurt(EventPlayerHurt eventInfo, GameEventInfo info) in S:\ROGLX NETWORK\server\scripts_tomade\Advanced Friendly Fire\advanced_friendlyfire.cs:line 101
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
   ```

**Comment by phara1** [comment]
https://github.com/phara1/advanced-ff-cs2/releases/tag/v1.1.2
This should fix it, let me know if you encounter any issues

**Comment by crashzk** [comment]
Fix
